server:
  port: 8022
  servlet:
    context-path: /

spring:
  application:
    name: feign-service

eureka:
  instance:
    instance-id: feign-service1-8022
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8010/eureka

