server:
  port: 8081

spring:
  application:
    name: nacos-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: '*'