server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: jhy

mybatis:
  config-location: classpath:mybatis/config/mybatis.xml
  type-aliases-package: com.jhy.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml


