server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: hystrix-client

# eureka的配置
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8010/eureka

# 服务访问地址
user-service-url: http://hystrix-service/
