server:
  port: 8080

spring:
  application:
    name: consul-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: consul-service1
          uri: http://localhost:8081/
          predicates:
            - Path=/service1/**
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback

        - id: consul-service2
          uri: http://localhost:8082/
          predicates:
            - Path=/service2/**
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: '*'


