server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: springcloud-client

# eureka的配置
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8010/eureka

# feign的配置
feign:
  hystrix:
    enabled: true

# 日志的配置
logging:
  level:
    com.jhy.springcloudclient.service.UserService: debug

# 服务访问地址
user-service-url: http://springcloud-service/
