server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: consul-client-8080
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

# feign的配置
feign:
  hystrix:
    enabled: true

